baseURL = "https://lakto.pupraki.com/"
languageCode = "zh-HK"
title = "Lakto's Burrow"
theme = "m10c"
publishDir = "docs"


[params]
    author = "Lakto"
    avatar = "avatar.jpg"
    description = "Lakto is the perfect partner for tea, and a beverage made from Raki."

    [[params.social]]
        name = "facebook"
        url = "https://www.facebook.com/puplakto"

    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/PupLakto"

    [params.style]
        darkestColor = "#ffffff" # charcoal
        darkColor = "#253031"
        primaryColor = "#315659"
        lightColor = "#a2a2a2"
        lightestColor = "#d3d3d3"
